//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafýndan oluþturuldu.
//     Çalýþma Zamaný Sürümü: 4.0.30319.42000
//
//     Bu dosyada yapýlan deðiþiklikler yanlýþ davranýþa yol açabilir ve þu durumda kaybolur
//     kod yeniden oluþturulduðunda.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünTakip.Properties
{


    /// <summary>
    ///   Yerelleþtirilmiþ dizeleri vs. aramak için türü kesin belirlenmiþ bir kaynak sýnýfý.
    /// </summary>
    // Bu sýnýf, StronglyTypedResourceBuilder tarafýndan otomatik olarak
    // ResGen ya da Visual Studio gibi bir araç ile oluþturuldu.
    // Bir üye eklemek ya da kaldýrmak için .ResX dosyanýzý düyenleyin, sonra da ResGen
    // öðesini /str seçeneðiyle yeniden çalýþtýrýn veya VS projenizi yeniden derleyin.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Bu sýnýf tarafýndan kullanýlan, önbelleðe alýnmýþ ResourceManager örneðini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ÜrünTakip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Geçerli iþ parçacýðýnýn CurrentUICulture özelliðini, türü kesin belirlenmiþ
        ///   bu kaynak sýnýfýný kullanan tüm kaynak aramalarý için geçersiz kýlar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
