﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir ara� taraf�ndan olu�turuldu.
//     �al��ma Zaman� S�r�m�: 4.0.30319.42000
//
//     Bu dosyada yap�lan de�i�iklikler yanl�� davran��a yol a�abilir ve �u durumda kaybolur
//     kod yeniden olu�turuldu�unda.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünTakip.Properties
{


    /// <summary>
    ///   Yerelle�tirilmi� dizeleri vs. aramak i�in t�r� kesin belirlenmi� bir kaynak s�n�f�.
    /// </summary>
    // Bu s�n�f, StronglyTypedResourceBuilder taraf�ndan otomatik olarak
    // ResGen ya da Visual Studio gibi bir ara� ile olu�turuldu.
    // Bir �ye eklemek ya da kald�rmak i�in .ResX dosyan�z� d�yenleyin, sonra da ResGen
    // ��esini /str se�ene�iyle yeniden �al��t�r�n veya VS projenizi yeniden derleyin.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Bu s�n�f taraf�ndan kullan�lan, �nbelle�e al�nm�� ResourceManager �rne�ini d�nd�r�r.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ÜrünTakip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Ge�erli i� par�ac���n�n CurrentUICulture �zelli�ini, t�r� kesin belirlenmi�
        ///   bu kaynak s�n�f�n� kullanan t�m kaynak aramalar� i�in ge�ersiz k�lar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
